name: Build and Deploy to Docker hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DATABASE_URL
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Build and push Docker user image
      env:
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.user
        no-cache: true
        secrets: |
          "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" 
        push: true
        tags: lokesh1129/paytm-clone-user:latest

    - name: Build and push Docker webhook image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.webhook
        push: true
        tags: lokesh1129/paytm-clone-webhook:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull lokesh1129/paytm-clone-user:latest
          sudo docker pull lokesh1129/paytm-clone-webhook:latest
          sudo docker stop paytm-clone-user || true
          sudo docker stop paytm-clone-webhook || true
          sudo docker rm paytm-clone-user || true
          sudo docker rm paytm-clone-webhook || true
          sudo docker network disconnect my_network paytm-clone-user
          sudo docker network disconnect my_network paytm-clone-webhook
          sudo docker network create my_network
          sudo docker run -d --name paytm-clone-user --name my_network -e AUTH_SECRET=${{ secrets.AUTH_SECRET }} -e AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }} -e AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -p 3000:3000 lokesh1129/paytm-clone-user:latest
          sudo docker run -d --name paytm-clone-webhook --name my_network -e DATABASE_URL=${{ secrets.DATABASE_URL }} lokesh1129/paytm-clone-webhook:latest